### ISSUE TITLE
[feature request] is there a way to run rgflow for the files in the quickfix list?

### ISSUE THREAD

**Issue by angelidis** [mangelozzi/rgflow.nvim#19]
hi mangelozzi!

LOVE this plugin -- thanks so much for releasing it!

I have a question, is there a way to run rgflow for the files that are already populated in the quickfix list?

here is a use case:

You want to rg a bunch of files that contain the word "one", only if they contain the word "two", on the command line you can do sth like this:

`rg "one" $(rg -w "two" -g "*.md" -l)`

how do you deal with cases like this?
where you want to drill down the list of files you've already identified.

**Comment by mangelozzi** [comment]
Hi, thanks for the positive feedback!
Do you know about `:Cfilter` and `Cfilter!`? That will solve the case if the phrase `one` and `two` are on the same line.

Can you give a real life example of searches you do with the above methodology to help me understand.

Cheers!

**Comment by mangelozzi** [comment]
Well since there was no reply, I just implemented what I think make sense, this was added to the readme:

> To limit searching to use only the list of files from your current quickfix list, use the magic string qf.
E.g. Say you searched for the pattern foo in ~/codebase, and you get a list of result in your quickfix list, now you wish to search for the phrase bar, but only search in the files that already had foo in them. By setting the path to qf, the path will be replaced with a list of filenames generated from the current quickfix list.

Feel free to open the issue again if it does not meet your needs.
